# Generated by Django 3.0.10 on 2020-11-01 22:58

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100, verbose_name='Коммент')),
                ('item_uid', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(max_length=30, verbose_name='Статус')),
                ('warranty_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
