# Generated by Django 3.0.10 on 2020-11-02 22:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_count', models.IntegerField(blank=True, default='', null=True)),
                ('model', models.CharField(default='', max_length=50)),
                ('size', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canceled', models.BooleanField(default=False)),
                ('order_item_uid', models.UUIDField(default=uuid.uuid4)),
                ('order_uid', models.UUIDField(default=uuid.uuid4)),
                ('item_id', models.IntegerField(blank=True, default='', null=True)),
            ],
        ),
    ]
