# Generated by Django 3.1.2 on 2020-10-26 01:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter field name', max_length=20, verbose_name='Имя')),
                ('user_uid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
