# Generated by Django 3.1.2 on 2020-10-27 01:15

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_uid', models.UUIDField(default=uuid.uuid4)),
                ('order_date', models.DateField(default=datetime.datetime.now)),
                ('order_uid', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('user_uid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
