name: Micro services

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Migrate
      run: |
        python3 warranty_service/manage.py migrate
    - name: Deploy Warranty service
      uses: akhileshns/heroku-deploy@v3.4.6
      with:
        heroku_api_key: 9bb8f29a-3dab-4878-86a3-33ab7960a1cb
        heroku_app_name: warranty-ivan
        heroku_email: Chernov-ivan.1997@yandex.ru
        appdir: warranty_service

